export const API = (import.meta.env.VITE_API_URL || 'http://localhost:8080').replace(/\/$/, '')

export type Job = { id:string; nomeArquivo:string; status:string; progresso:number; etapa:string; mensagem:string; criadoEm:string; atualizadoEm:string; resultado?:AnalysisResult|null; analiseEspecializada?:unknown }
export type AnalysisResult = { metadata?:any; partes?:any[]; cronologia?:any[]; pedidos?:any[]; decisoes?:any[]; prazos?:any[]; documentosImportantes?:any[]; resumoProcesso?:string; inconsistencias?:any[]; gruposEvidencia?:any[]; perguntasInvestigacao?:string[]; relatorioExecutivo?:any; analiseEspecializada?:any }
export type Briefing = { analiseId:string; numeroProcesso:string; nomeArquivo:string; geradoEm:string; partes:any[]; situacao?:any; linhaDoTempo:any[]; pontosAtencao:any[]; evidencias:any[]; perguntasParaOAdvogado:any[]; avisos:string[]; markdown:string }
export type ChatResponse = { sessaoId:string; pergunta:string; resposta:string; citacoes:any[]; fundamentada:boolean; modoRecuperacao:string; perguntasSugeridas:string[]; aviso:string }
export type DataJudInfo = { status?:string; numeroProcesso?:string|null; tribunal?:string|null; endpoint?:string|null; encontrado?:boolean; quantidadeMovimentos?:number|null; ultimaMovimentacao?:string|null; classeProcessual?:string|null; orgaoJulgador?:string|null; grau?:string|null; mensagem?:string|null; consultadoEm?:string|null; movimentos?:any[] }
export type DataJudSample = { numeroProcesso?:string|null; codigoClasse?:string|null; classe?:string|null; assuntos?:string[]; grau?:string|null; orgaoJulgador?:string|null; dataAjuizamento?:string|null; ultimaMovimentacao?:string|null; possuiBaixa?:boolean }
export type DataJudSearchResponse = { id:string; tipo:string; tribunal?:string|null; criterio?:string|null; sucesso:boolean; mensagem?:string|null; consultadoEm?:string|null; info?:DataJudInfo|null; amostra?:DataJudSample[]; quantidade?:number }
export type DataJudPesquisa = { id:string; tipo:string; parametro?:string|null; tribunal?:string|null; assunto?:string|null; numeroCnj?:string|null; classeCodigo?:string|null; classeNome?:string|null; grau?:string|null; orgaoJulgador?:string|null; resultadoEncontrado:boolean; processado:boolean; analiseId?:string|null; mensagem?:string|null; consultadoEm?:string; criadoEm?:string }
export type ProcessoLista = { id:string; nomeArquivo:string; numeroCnj?:string|null; status:string; progresso:number; etapa?:string; mensagem?:string; criadoEm:string; atualizadoEm:string; relatorioBaseDisponivel:boolean; analiseEspecializadaId?:string|null; analiseEspecializadaStatus?:string|null; analiseEspecializadaProgresso:number; analiseEspecializadaEtapa?:string|null; relatorioEspecializadoDisponivel:boolean }
async function parse<T>(r:Response):Promise<T>{const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.message||body.error||`Erro HTTP ${r.status}`);return body}
export async function uploadPdf(file:File){const fd=new FormData();fd.append('arquivo',file);return parse<Job>(await fetch(`${API}/api/v1/processos/analisar`,{method:'POST',body:fd}))}
export async function getJob(id:string){return parse<Job>(await fetch(`${API}/api/v1/processos/analises/${id}`))}
export async function listProcessos(){return parse<ProcessoLista[]>(await fetch(`${API}/api/v1/processos`))}
export async function getBriefing(id:string){return parse<Briefing>(await fetch(`${API}/api/v1/processos/analises/${id}/briefing`))}
export async function askProcess(id:string,pergunta:string,sessaoId?:string){return parse<ChatResponse>(await fetch(`${API}/api/v1/processos/analises/${id}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pergunta,...(sessaoId?{sessaoId}:{})})}))}
export async function startSpecialized(id:string,payload:any={}){return parse<any>(await fetch(`${API}/api/v1/processos/analises/${id}/especializada`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}))}
export async function getSpecialized(id:string){return parse<any>(await fetch(`${API}/api/v1/processos/analises-especializadas/${id}`))}
export function baseReportUrl(id:string){return `${API}/api/v1/processos/analises/${id}/relatorio-pdf`}
export function specializedReportUrl(id:string){return `${API}/api/v1/processos/analises-especializadas/${id}/relatorio-pdf`}
export async function searchProcessByCnj(numeroProcesso:string){return parse<DataJudSearchResponse>(await fetch(`${API}/api/v1/datajud/processos/cnj?numeroProcesso=${encodeURIComponent(numeroProcesso)}`))}
export async function searchProcessByCpf(cpf:string,tribunal?:string){const params=new URLSearchParams({cpf});if(tribunal?.trim())params.set('tribunal',tribunal.trim());return parse<DataJudSearchResponse>(await fetch(`${API}/api/v1/datajud/processos/cpf?${params.toString()}`))}
export async function searchProcessBySubject(tribunal:string,assunto:string,tamanho=10){const params=new URLSearchParams({codigoTribunal:tribunal,assunto,tamanho:String(tamanho)});return parse<DataJudSearchResponse>(await fetch(`${API}/api/v1/datajud/processos/amostra?${params.toString()}`))}
export async function processFoundCnj(numeroProcesso:string){return parse<Job>(await fetch(`${API}/api/v1/datajud/processos/cnj/processar?numeroProcesso=${encodeURIComponent(numeroProcesso)}`,{method:'POST'}))}
export async function processFoundCpf(cpf:string,tribunal?:string){const params=new URLSearchParams({cpf});if(tribunal?.trim())params.set('tribunal',tribunal.trim());return parse<Job>(await fetch(`${API}/api/v1/datajud/processos/cpf/processar?${params.toString()}`,{method:'POST'}))}
export async function processFoundSample(numeroProcesso:string){return parse<Job>(await fetch(`${API}/api/v1/datajud/processos/amostra/processar?numeroProcesso=${encodeURIComponent(numeroProcesso)}`,{method:'POST'}))}
export async function listDataJudPesquisas(){return parse<DataJudPesquisa[]>(await fetch(`${API}/api/v1/datajud/pesquisas`))}
