import { useState } from 'react'
import { Loader2, Search, Play } from 'lucide-react'

const API=(import.meta.env.VITE_API_URL||'http://localhost:8080').replace(/\/$/,'')
const ACTIVE_JOB_KEY='legal-analyzer:active-job-id'

export default function ProcessSearchBar(){
 const [mode,setMode]=useState<'CNJ'|'CPF'|'TPU'>('CNJ');const [value,setValue]=useState('');const [tribunal,setTribunal]=useState('tjsp');const [loading,setLoading]=useState(false);const [message,setMessage]=useState('')
 async function run(processar:boolean){if(!value.trim())return;setLoading(true);setMessage('');try{let url='';let init:RequestInit={method:processar?'POST':'GET'};if(mode==='CNJ')url=`${API}/api/v1/datajud/processos/cnj${processar?'/processar':''}?numeroProcesso=${encodeURIComponent(value)}`;else if(mode==='CPF')url=`${API}/api/v1/datajud/processos/cpf${processar?'/processar':''}?cpf=${encodeURIComponent(value)}&tribunal=${encodeURIComponent(tribunal)}`;else url=`${API}/api/v1/datajud/processos/amostra?codigoTribunal=${encodeURIComponent(tribunal)}&assunto=${encodeURIComponent(value)}&tamanho=8`;const r=await fetch(url,init);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.error||`HTTP ${r.status}`);if(processar&&b.id){localStorage.setItem(ACTIVE_JOB_KEY,b.id);window.location.reload();return}setMessage(b.mensagem||`Consulta concluída. ${b.amostra?.length??b.processo?'Processo localizado.':'Nenhum resultado.'}`)}catch(e:any){setMessage(e.message||'Falha na consulta.')}finally{setLoading(false)}}
 return <div className="process-search-bar"><div className="process-search-title"><Search size={17}/><div><b>Pesquisar processo</b><small>CNJ, CPF ou Tribunal + assunto TPU</small></div></div><div className="process-search-tabs">{(['CNJ','CPF','TPU'] as const).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>{setMode(m);setValue('');setMessage('')}}>{m}</button>)}</div><div className="process-search-fields">{mode==='TPU'&&<input value={tribunal} onChange={e=>setTribunal(e.target.value)} placeholder="Tribunal"/>}<input value={value} onChange={e=>setValue(e.target.value)} placeholder={mode==='CNJ'?'0000000-00.0000.0.00.0000':mode==='CPF'?'CPF do interessado':'Código ou assunto TPU'} onKeyDown={e=>e.key==='Enter'&&run(false)}/><button onClick={()=>run(false)} disabled={loading}>{loading?<Loader2 className="spin" size={16}/>:<Search size={16}/>} Pesquisar</button>{mode!=='TPU'&&<button className="process-search-primary" onClick={()=>run(true)} disabled={loading}><Play size={15}/> Pesquisar e analisar</button>}</div>{mode==='CPF'&&<div className="process-search-hint">A pesquisa por CPF depende dos dados efetivamente disponibilizados pelo DataJud; ausência de resultado não significa inexistência de processos.</div>}{message&&<div className="process-search-message">{message}</div>}</div>
}
